AlgebraSeminar/Controllers/Pre_RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AlgebraSeminar.Models;

namespace AlgebraSeminar.Controllers
{
    public class Pre_RegistrationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult Index()
        {
            var pre_Registration = db.Pre_Registration.Include(p => p.Course);
            return View(pre_Registration.ToList());
        }

        public ActionResult IndexAccepted()
        {
            var pre_Registration = db.Pre_Registration.Include(p => p.Course);
            return View(pre_Registration.ToList().Where(x => x.Status == true));
        }

        public ActionResult IndexDeclineded()
        {
            var pre_Registration = db.Pre_Registration.Include(p => p.Course);
            return View(pre_Registration.ToList().Where(x => x.Status != true && x.Status != null));
        }

        public ActionResult IndexUncommitted()
        {
            var pre_Registration = db.Pre_Registration.Include(p => p.Course);
            return View(pre_Registration.ToList().Where(x => x.Status == null));
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pre_Registration pre_Registration = db.Pre_Registration.Find(id);
            if (pre_Registration == null)
            {
                return HttpNotFound();
            }
            return View(pre_Registration);
        }

        
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Course.Where(x => x.Filled != true), "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,PhoneNumber,Status,CourseId")] Pre_Registration pre_Registration)
        {
            if (ModelState.IsValid)
            {
                db.Pre_Registration.Add(pre_Registration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Course.Where(x => x.Filled != true), "Id", "Name", pre_Registration.CourseId);
            return View(pre_Registration);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pre_Registration pre_Registration = db.Pre_Registration.Find(id);
            if (pre_Registration == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Course.Where(x => x.Filled != true), "Id", "Name", pre_Registration.CourseId);
            return View(pre_Registration);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,PhoneNumber,Status,CourseId")] Pre_Registration pre_Registration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pre_Registration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Course.Where(x => x.Filled != true), "Id", "Name", pre_Registration.CourseId);
            return View(pre_Registration);
        }

        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pre_Registration pre_Registration = db.Pre_Registration.Find(id);
            if (pre_Registration == null)
            {
                return HttpNotFound();
            }
            return View(pre_Registration);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pre_Registration pre_Registration = db.Pre_Registration.Find(id);
            db.Pre_Registration.Remove(pre_Registration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

AlgebraSeminar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Algebra app", "Create", "Pre_Registration", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pre-Registration", "Create", "Pre_Registration")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                    <li>
                        @if (Request.IsAuthenticated)
                        {
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Pre-Registrations</button>
                            <ul class="dropdown-menu">
                                <li><a href="~/Pre_Registration/Index">List of all pre-registrations</a></li>
                                <li><a href="~/Pre_Registration/IndexAccepted">List of accepted pre-registrations</a></li>
                                <li><a href="~/Pre_Registration/IndexDeclineded">List of declinded pre-registrations</a></li>
                                <li><a href="~/Pre_Registration/IndexUncommitted">List of uncommitted pre-registrations</a></li>
                            </ul>
                        </div>
                        }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>